module.exports = {
  Dalarna: {
    id: 15,
    passportId: 27,
    cardId: 26,
    locations: {
      Avesta: 50,
      Borlänge: 6,
      Ludvika: 55,
      Mora: 56,
    },
  },
  Jamtland: {
    id: 18,
    locations: {
      Funäsdalen: 62,
      Strömsund: 73,
      Sveg: 74,
      Åre: 77,
      Östersund: 9,
    },
  },
  Stockholm: {
    id: 47,
    locations: {
      Flemingsberg: 38,
      Globen: 40,
      Haninge: 46,
      Järva: 113,
      Nacka: 45,
      Norrtälje: 44,
      Sollentuna: 43,
      Solna: 42,
      "Sthlm City": 41,
      Södertälje: 47,
      "Södra Roslagen": 48,
    },
  },
  Skane: {
    id: 77,
    locations: {
      Eslöv: 110,
      Helsingborg: 111,
      Hässleholm: 108,
      Klippan: 67,
      Kristianstad: 109,
      Landskrona: 114,
      Lund: 118,
      Malmö: 112,
      Trelleborg: 116,
      Ystad: 117,
      Ängelholm: 115,
    },
  },
  Blekinge: {
    id: 74,
    passportId: 76,
    cardId: 75,
    locations: {
      Karlshamn: 106,
      Karlskrona: 105,
    },
  },
  VastraGotaland: {
    id: 40,
    locations: {
      Alingsås: 17,
      Borås: 18,
      Falköping: 24,
      Göteborg: 15,
      Lidköping: 31,
      Mariestad: 26,
      "Mark/Kinna": 19,
      Mölndal: 16,
      Skövde: 27,
      Stenungsund: 28,
      Strömstad: 29,
      Trollhättan: 30,
      Uddevalla: 25,
      Ulricehamn: 20,
      Åmål: 23,
    },
  },
  Norrbotten: {
    id: 53,
    passportId: 54,
    cardId: 55,
    locations: {
      Arvidsjaur: 60,
      Boden: 61,
      Gällivare: 63,
      Haparanda: 64,
      Kalix: 65,
      Kiruna: 66,
      Luleå: 79,
      Piteå: 70,
    },
  },
};
