module.exports = {
  Blekinge: {
    id: 74,
    passportId: 76,
    cardId: 75,
    locations: {
      Karlshamn: 106,
      Karlskrona: 105,
    },
  },
  Dalarna: {
    id: 15,
    passportId: 27,
    cardId: 26,
    locations: {
      Avesta: 50,
      Borlänge: 6,
      Ludvika: 55,
      Mora: 56,
    },
  },
  Gotland: {
    id: 21,
    passportId: 27,
    cardId: 26,
    locations: {
      Visby: 12,
    },
  },
  Gavleborg: {
    id: 19,
    passportId: 29,
    cardId: 28,
    locations: {
      Bollnäs: 37,
      Gävle: 13,
      Hudiksvall: 32,
    },
  },
  Halland: {
    id: 65,
    passportId: 67,
    cardId: 66,
    locations: {
      Falkenberg: 96,
      Halmstad: 97,
      Kungsbacka: 94,
      Varberg: 95,
    },
  },
  Jamtland: {
    id: 18,
    passportId: 31,
    cardId: 30,
    locations: {
      Funäsdalen: 62,
      Strömsund: 73,
      Sveg: 74,
      Åre: 77,
      Östersund: 9,
    },
  },
  Jonkoping: {
    id: 59,
    passportId: 64,
    cardId: 63,
    locations: {
      Eksjö: 82,
      Jönköping: 83,
      Värnamo: 84,
    },
  },
  Kalmar: {
    id: 69,
    passportId: 72,
    cardId: 73,
    locations: {
      Kalmar: 102,
      Oskarshamn: 103,
      Västervik: 104,
    },
  },
  Kronoberg: {
    id: 68,
    passportId: 71,
    cardId: 70,
    locations: {
      Ljungby: 98,
      Växjö: 99,
      Älmhult: 100,
    },
  },
  Norrbotten: {
    id: 53,
    passportId: 54,
    cardId: 55,
    locations: {
      Arvidsjaur: 60,
      Boden: 61,
      Gällivare: 63,
      Haparanda: 64,
      Kalix: 65,
      Kiruna: 66,
      Luleå: 79,
      Piteå: 70,
    },
  },
  Skane: {
    id: 77,
    passportId: 79,
    cardId: 78,
    locations: {
      Eslöv: 110,
      Helsingborg: 111,
      Hässleholm: 108,
      Klippan: 67,
      Kristianstad: 109,
      Landskrona: 114,
      Lund: 118,
      Malmö: 112,
      Trelleborg: 116,
      Ystad: 117,
      Ängelholm: 115,
    },
  },
  Stockholm: {
    id: 47,
    passportId: 52,
    cardId: 48,
    locations: {
      Flemingsberg: 38,
      Globen: 40,
      Haninge: 46,
      Järva: 113,
      Nacka: 45,
      Norrtälje: 44,
      Sollentuna: 43,
      Solna: 42,
      "Sthlm City": 41,
      Södertälje: 47,
      "Södra Roslagen": 48,
    },
  },
  Sodermanland: {
    id: 60,
    passportId: 62,
    cardId: 61,
    locations: {
      Eskilstuna: 85,
      Katrineholm: 86,
      Nyköping: 87,
      Skavsta: 88,
      Strängnäs: 89,
    },
  },
  Uppsala: {
    id: 20,
    passportId: 25,
    cardId: 24,
    locations: {
      Enköping: 3,
      Tierp: 34,
      Uppsala: 5,
      Östhammar: 33,
    },
  },
  Varmland: {
    id: 16,
    passportId: 23,
    cardId: 22,
    locations: {
      Arvika: 49,
      Karlstad: 7,
      Kristinehamn: 53,
      Torsby: 57,
    },
  },
  Vasterbotten: {
    id: 13,
    passportId: 35,
    cardId: 34,
    locations: {
      Lycksele: 69,
      Skellefteå: 11,
      Storuman: 72,
      Umeå: 81,
      Vilhelmina: 75,
    },
  },
  Vasternorrland: {
    id: 14,
    passportId: 37,
    cardId: 36,
    locations: {
      Härnösand: 10,
      Kramfors: 68,
      Sollefteå: 71,
      Sundsvall: 80,
      Ånge: 76,
      Örnsköldsvik: 78,
    },
  },
  Vastmanland: {
    id: 1,
    passportId: 3,
    cardId: 2,
    locations: {
      Fagersta: 36,
      Köping: 2,
      Sala: 35,
      Västerås: 93,
    },
  },
  VastraGotaland: {
    id: 40,
    passportId: 42,
    cardId: 41,
    locations: {
      Alingsås: 17,
      Borås: 18,
      Falköping: 24,
      Göteborg: 15,
      Lidköping: 31,
      Mariestad: 26,
      "Mark/Kinna": 19,
      Mölndal: 16,
      Skövde: 27,
      Stenungsund: 28,
      Strömstad: 29,
      Trollhättan: 30,
      Uddevalla: 25,
      Ulricehamn: 20,
      Åmål: 23,
    },
  },
  Orebro: {
    id: 17,
    passportId: 39,
    cardId: 38,
    locations: {
      Hallsberg: 51,
      Karlskoga: 52,
      Lindesberg: 54,
      Vivalla: 58,
      Örebro: 8,
    },
  },
  Ostergotland: {
    id: 56,
    passportId: 58,
    cardId: 57,
    locations: {
      Linköping: 90,
      Motala: 91,
      Norrköping: 92,
    },
  },
};
